SYM_SPACE = '_'
SYM_UNK = '<UNK>'
SYM_BOL = '^'
SYM_IDENT = '.'
SYM_SPLIT = '='
SYM_PAD = '#'

HDF5_KEY_TRAIN_IXES = 'train_ixes'
HDF5_KEY_TEST_IXES = 'test_ixes'
HDF5_KEY_VALID_IXES = 'valid_ixes'
HDF5_KEY_SEN_LENS = 'sen_lens'
HDF5_KEY_SPLIT_CNTS = 'split_cnts'
HDF5_KEY_INPUT = 'input'
HDF5_KEY_OUTPUT= 'output'

ADD_KEY_DEENC_INPUT = 'de-enc-input'
ADD_KEY_DEENC_OUTPUT= 'de-enc-output'
ADD_KEY_SPLITCNTS_NGRAMS_LEFT = 'splitcnts-ngrams-left'
ADD_KEY_SPLITCNTS_NGRAMS_RIGHT= 'splitcnts-ngrams-right'
ADD_KEY_SPLITCNTS_MAXLEN = 'splitcnts-maxlen'
ADD_KEY_SPLITCNTS_MINLEN = 'splitcnts-minlen'
ADD_KEY_SPLITCNTS_MINMAX = 'splitcnts-minmaxes'

''' keys for saving and restoring '''
KEY_X = 'x'
KEY_SPLIT_CNTS = 'splitcnts'
KEY_SEQLENS = 'seqlens'
KEY_DROPOUT = 'dropout'
KEY_PREDICTIONS = 'predictions'
